<?php

use Illuminate\Database\Seeder;

class BanksTableSeeder extends Seeder
{

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $now = date('Y-m-d H:i:s');

        DB::table('banks')->insert([

            [
                'id'                => 105680,
                'name'              => 'ABC Brasil Distribuidora de Títulos e Valores Mobiliários S.A.',
                'website'           => 'http://www.abcbrasil.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 104512,
                'name'              => 'Banco de Desenvolvimento do Estado de Santa Catarina S.A.',
                'website'           => null,
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105681,
                'name'              => 'Agiplan Financeira S.A. - Crédito Financiamento e Investimento',
                'website'           => 'http://www.agiplanfinanceira.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105659,
                'name'              => 'Ágora Corretora de Títulos e Valores Mobiliários S.A.',
                'website'           => 'http://www.agorainvest.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105684,
                'name'              => 'Alfa Arrendamento Mercantil S.A.',
                'website'           => 'http://www.alfanet.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105685,
                'name'              => 'Alfa Corretora de Câmbio e Valores Mobiliários S.A.',
                'website'           => 'http://www.alfanet.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105702,
                'name'              => 'Bacor Corretora de Câmbio e Valores Mobiliários S.A.',
                'website'           => 'http://www.bancobbm.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105703,
                'name'              => 'Bahia Administração de Recursos Distribuidora de Títulos e Valores Mobiliários S.A.',
                'website'           => 'http://www.bancobbm.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 104054,
                'name'              => 'Banco A.J.Renner S.A.',
                'website'           => 'http://www.bancorenner.com.br',
                'compensation_code' => 654,
                'created_at'        => $now,
            ],
            [
                'id'                => 103988,
                'name'              => 'Banco ABC Brasil S.A.',
                'website'           => 'http://www.abcbrasil.com.br',
                'compensation_code' => 246,
                'created_at'        => $now,
            ],
            [
                'id'                => 105461,
                'name'              => 'Banco CR2 S.A.',
                'website'           => 'http://www.bancocr2.com.br',
                'compensation_code' => 75,
                'created_at'        => $now,
            ],
            [
                'id'                => 105541,
                'name'              => 'Banco Agibank S.A.',
                'website'           => 'http://www.agibank.com.br',
                'compensation_code' => 121,
                'created_at'        => $now,
            ],
            [
                'id'                => 7,
                'name'              => 'Banco Alfa de Investimentos S.A.',
                'website'           => 'http://www.alfanet.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 103999,
                'name'              => 'Banco Alfa S.A.',
                'website'           => 'http://www.bancoalfa.com.br',
                'compensation_code' => 25,
                'created_at'        => $now,
            ],
            [
                'id'                => 104050,
                'name'              => 'Banco Alvorada S.A.',
                'website'           => null,
                'compensation_code' => 641,
                'created_at'        => $now,
            ],
            [
                'id'                => 103950,
                'name'              => 'Banco Patagon S.A.',
                'website'           => null,
                'compensation_code' => 65,
                'created_at'        => $now,
            ],
            [
                'id'                => 103969,
                'name'              => 'Banco Arbi S.A.',
                'website'           => 'http://www.arbi.com.br',
                'compensation_code' => 213,
                'created_at'        => $now,
            ],
            [
                'id'                => 103928,
                'name'              => 'Banco BANDEPE S.A.',
                'website'           => 'http://www.santander.com.br',
                'compensation_code' => 24,
                'created_at'        => $now,
            ],
            [
                'id'                => 103954,
                'name'              => 'Banco BOCOM BBM S.A.',
                'website'           => 'http://www.bancobbm.com.br',
                'compensation_code' => 107,
                'created_at'        => $now,
            ],
            [
                'id'                => null,
                'name'              => 'Banco BM&amp;FBOVESPA de Serviços de Liquidação e Custódia S.A',
                'website'           => 'http://www.bmfbovespa.com.br/bancobmfbovespa/',
                'compensation_code' => 96,
                'created_at'        => $now,
            ],
            [
                'id'                => 104001,
                'name'              => 'Banco BMG S.A.',
                'website'           => 'http://www.bancobmg.com.br',
                'compensation_code' => 318,
                'created_at'        => $now,
            ],
            [
                'id'                => 104076,
                'name'              => 'Banco BNP Paribas Brasil S.A.',
                'website'           => 'http://www.bnpparibas.com.br',
                'compensation_code' => 752,
                'created_at'        => $now,
            ],
            [
                'id'                => 103948,
                'name'              => 'Ibibank S.A. - Banco Múltiplo',
                'website'           => null,
                'compensation_code' => 63,
                'created_at'        => $now,
            ],
            [
                'id'                => 103937,
                'name'              => 'Banco Bradesco BBI S.A.',
                'website'           => null,
                'compensation_code' => 36,
                'created_at'        => $now,
            ],
            [
                'id'                => 104256,
                'name'              => 'Banco Bradesco BERJ S.A.',
                'website'           => null,
                'compensation_code' => 122,
                'created_at'        => $now,
            ],
            [
                'id'                => 103963,
                'name'              => 'Banco Bradesco Cartões S.A.',
                'website'           => null,
                'compensation_code' => 204,
                'created_at'        => $now,
            ],
            [
                'id'                => 104014,
                'name'              => 'Banco Bradesco Financiamentos S.A.',
                'website'           => null,
                'compensation_code' => 394,
                'created_at'        => $now,
            ],
            [
                'id'                => 103984,
                'name'              => 'Banco Bradesco S.A.',
                'website'           => 'http://www.bradesco.com.br',
                'compensation_code' => 237,
                'created_at'        => $now,
            ],
            [
                'id'                => 103973,
                'name'              => 'Banco BS2 S.A.',
                'website'           => 'http://www.bs2.com/banco/',
                'compensation_code' => 218,
                'created_at'        => $now,
            ],
            [
                'id'                => 103965,
                'name'              => 'Banco BTG Pactual S.A.',
                'website'           => 'http://www.btgpactual.com',
                'compensation_code' => 208,
                'created_at'        => $now,
            ],
            [
                'id'                => 104023,
                'name'              => 'Banco Financial Português S.A.',
                'website'           => null,
                'compensation_code' => 473,
                'created_at'        => $now,
            ],
            [
                'id'                => 104017,
                'name'              => 'Banco Capital S.A.',
                'website'           => 'http://www.bancocapital.com.br',
                'compensation_code' => 412,
                'created_at'        => $now,
            ],
            [
                'id'                => 103941,
                'name'              => 'Banco Cargill S.A.',
                'website'           => 'http://www.bancocargill.com.br',
                'compensation_code' => 40,
                'created_at'        => $now,
            ],
            [
                'id'                => 105582,
                'name'              => 'Banco Caterpillar S.A.',
                'website'           => 'http://www.catfinancial.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105642,
                'name'              => 'Banco CBSS S.A.',
                'website'           => 'http://www.aebb.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 103997,
                'name'              => 'Banco Cédula S.A.',
                'website'           => 'http://www.bancocedula.com.br',
                'compensation_code' => 266,
                'created_at'        => $now,
            ],
            [
                'id'                => 104065,
                'name'              => 'Banco Cetelem S.A.',
                'website'           => 'http://www.cetelem.com.br',
                'compensation_code' => 739,
                'created_at'        => $now,
            ],
            [
                'id'                => 103982,
                'name'              => 'Banco Cifra S.A.',
                'website'           => 'http://www.bancocifra.com.br',
                'compensation_code' => 233,
                'created_at'        => $now,
            ],
            [
                'id'                => 104070,
                'name'              => 'Banco Citibank S.A.',
                'website'           => 'http://www.citibank.com.br',
                'compensation_code' => 745,
                'created_at'        => $now,
            ],
            [
                'id'                => 103985,
                'name'              => 'Banco Clássico S.A.',
                'website'           => 'http://www.bancoclassico.com.br',
                'compensation_code' => 241,
                'created_at'        => $now,
            ],
            [
                'id'                => 104095,
                'name'              => 'Banco CNH Industrial Capital S.A.',
                'website'           => 'http://www.cnhindustrialcapital.com',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105578,
                'name'              => 'Banco Confidence de Câmbio S.A.',
                'website'           => 'http://www.bancoconfidence.com.br',
                'compensation_code' => 95,
                'created_at'        => $now,
            ],
            [
                'id'                => 104079,
                'name'              => 'Banco Cooperativo do Brasil S.A. - BANCOOB',
                'website'           => 'http://www.bancoob.com.br',
                'compensation_code' => 756,
                'created_at'        => $now,
            ],
            [
                'id'                => 104073,
                'name'              => 'Banco Cooperativo Sicredi S.A.',
                'website'           => 'http://www.sicredi.com.br',
                'compensation_code' => 748,
                'created_at'        => $now,
            ],
            [
                'id'                => 103975,
                'name'              => 'Banco Credit Agricole Brasil S.A.',
                'website'           => 'http://www.calyon.com.br',
                'compensation_code' => 222,
                'created_at'        => $now,
            ],
            [
                'id'                => 104035,
                'name'              => 'Banco Credit Suisse (Brasil) S.A.',
                'website'           => 'http://www.csfb.com',
                'compensation_code' => 505,
                'created_at'        => $now,
            ],
            [
                'id'                => 105419,
                'name'              => 'Banco Crefisa S.A.',
                'website'           => 'http://www.crefisa.com.br',
                'compensation_code' => 69,
                'created_at'        => $now,
            ],
            [
                'id'                => 105492,
                'name'              => 'Banco CSF S.A.',
                'website'           => null,
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 103923,
                'name'              => 'Banco da Amazônia S.A.',
                'website'           => 'http://www.bancoamazonia.com.br',
                'compensation_code' => 3,
                'created_at'        => $now,
            ],
            [
                'id'                => 105532,
                'name'              => 'Banco da China Brasil S.A.',
                'website'           => 'http://www.boc-brazil.com',
                'compensation_code' => 83,
                'created_at'        => $now,
            ],
            [
                'id'                => 104057,
                'name'              => 'Banco Daycoval S.A.',
                'website'           => 'http://www.daycoval.com.br',
                'compensation_code' => 707,
                'created_at'        => $now,
            ],
            [
                'id'                => 5,
                'name'              => 'Banco de Investimento Credit Suisse (Brasil) S.A.',
                'website'           => 'http://www.csfb.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 104000,
                'name'              => 'Banco de La Nacion Argentina',
                'website'           => 'http://www.bna.com.ar',
                'compensation_code' => 300,
                'created_at'        => $now,
            ],
            [
                'id'                => 104032,
                'name'              => 'Banco de La Provincia de Buenos Aires',
                'website'           => 'http://www.bapro.com.ar',
                'compensation_code' => 495,
                'created_at'        => $now,
            ],
            [
                'id'                => 104031,
                'name'              => 'Banco de La Republica Oriental del Uruguay',
                'website'           => 'http://www.bancorepublica.com.uy',
                'compensation_code' => 494,
                'created_at'        => $now,
            ],
            [
                'id'                => 104926,
                'name'              => 'Banco de Lage Landen Brasil S.A.',
                'website'           => 'http://www.dllgroup.com',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 104020,
                'name'              => 'Banco MUFG Brasil S.A.',
                'website'           => 'http://www.br.bk.mufg.jp',
                'compensation_code' => 456,
                'created_at'        => $now,
            ],
            [
                'id'                => 103922,
                'name'              => 'Banco do Brasil S.A.',
                'website'           => 'http://www.bb.com.br',
                'compensation_code' => 1,
                'created_at'        => $now,
            ],
            [
                'id'                => 103944,
                'name'              => 'Banco do Estado de Sergipe S.A.',
                'website'           => 'http://www.banese.com.br',
                'compensation_code' => 47,
                'created_at'        => $now,
            ],
            [
                'id'                => 103938,
                'name'              => 'Banco do Estado do Pará S.A.',
                'website'           => 'http://www.banpara.b.br',
                'compensation_code' => 37,
                'created_at'        => $now,
            ],
            [
                'id'                => 103942,
                'name'              => 'Banco do Estado do Rio Grande do Sul S.A.',
                'website'           => 'http://www.banrisul.com.br',
                'compensation_code' => 41,
                'created_at'        => $now,
            ],
            [
                'id'                => 103924,
                'name'              => 'Banco do Nordeste do Brasil S.A.',
                'website'           => 'http://www.banconordeste.gov.br',
                'compensation_code' => 4,
                'created_at'        => $now,
            ],
            [
                'id'                => 103996,
                'name'              => 'Banco Fator S.A.',
                'website'           => 'http://www.fator.com.br',
                'compensation_code' => 265,
                'created_at'        => $now,
            ],
            [
                'id'                => 103976,
                'name'              => 'Banco Fibra S.A.',
                'website'           => 'http://www.bancofibra.com.br',
                'compensation_code' => 224,
                'created_at'        => $now,
            ],
            [
                'id'                => 104044,
                'name'              => 'Banco Ficsa S.A.',
                'website'           => 'http://www.ficsa.com.br',
                'compensation_code' => 626,
                'created_at'        => $now,
            ],
            [
                'id'                => 104920,
                'name'              => 'Banco Fidis S.A.',
                'website'           => 'http://www.bancofidis.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105553,
                'name'              => 'Banco Finaxis S.A.',
                'website'           => 'http://www.bancofinaxis.com.br',
                'compensation_code' => 94,
                'created_at'        => $now,
            ],
            [
                'id'                => 104094,
                'name'              => 'Banco Ford S.A.',
                'website'           => 'http://www.bancoford.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 104971,
                'name'              => 'Banco GMAC S.A.',
                'website'           => 'http://www.chevroletsf.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 104040,
                'name'              => 'Banco Guanabara S.A.',
                'website'           => 'http://www.bancoguanabara.com.br',
                'compensation_code' => 612,
                'created_at'        => $now,
            ],
            [
                'id'                => 104099,
                'name'              => 'Banco Honda S.A.',
                'website'           => 'http://www.bancohonda.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105454,
                'name'              => 'Banco IBM S.A.',
                'website'           => 'http://www.ibm.com/financing/br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105506,
                'name'              => 'Banco INBURSA de Investimentos S.A.',
                'website'           => 'http://www.bancoinbursa.com',
                'compensation_code' => 12,
                'created_at'        => $now,
            ],
            [
                'id'                => 103994,
                'name'              => 'Banco Induscred S.A.',
                'website'           => null,
                'compensation_code' => 258,
                'created_at'        => $now,
            ],
            [
                'id'                => 104037,
                'name'              => 'Banco Industrial do Brasil S.A.',
                'website'           => 'http://www.bancoindustrial.com.br',
                'compensation_code' => 604,
                'created_at'        => $now,
            ],
            [
                'id'                => 104053,
                'name'              => 'Banco Indusval S.A.',
                'website'           => 'http://www.bip.b.br',
                'compensation_code' => 653,
                'created_at'        => $now,
            ],
            [
                'id'                => 105515,
                'name'              => 'Banco Inter S.A.',
                'website'           => 'http://www.bancointer.com.br',
                'compensation_code' => 77,
                'created_at'        => $now,
            ],
            [
                'id'                => 104045,
                'name'              => 'Banco Intercap S.A.',
                'website'           => null,
                'compensation_code' => 630,
                'created_at'        => $now,
            ],
            [
                'id'                => 103990,
                'name'              => 'Banco Investcred S.A.',
                'website'           => null,
                'compensation_code' => 249,
                'created_at'        => $now,
            ],
            [
                'id'                => 103945,
                'name'              => 'Banco Itaú BBA S.A.',
                'website'           => 'http://www.itaubba.com.br',
                'compensation_code' => 184,
                'created_at'        => $now,
            ],
            [
                'id'                => 103931,
                'name'              => 'Banco Itaú Consignado S.A.',
                'website'           => null,
                'compensation_code' => 29,
                'created_at'        => $now,
            ],
            [
                'id'                => 104090,
                'name'              => 'Banco Itaú Veículos S.A.',
                'website'           => 'http://www.bancofiat.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 104025,
                'name'              => 'Banco ItauBank S.A',
                'website'           => 'http://www.itaubank.com.br',
                'compensation_code' => 479,
                'created_at'        => $now,
            ],
            [
                'id'                => 105524,
                'name'              => 'Banco Itaucard S.A.',
                'website'           => 'http://www.itau.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105540,
                'name'              => 'Banco Itauleasing S.A.',
                'website'           => 'http://www.itau.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 103943,
                'name'              => 'Banco J. Safra S.A.',
                'website'           => 'http://www.safra.com.br',
                'compensation_code' => 74,
                'created_at'        => $now,
            ],
            [
                'id'                => 104011,
                'name'              => 'Banco J. P. Morgan S.A.',
                'website'           => 'http://www.jpmorgan.com',
                'compensation_code' => 376,
                'created_at'        => $now,
            ],
            [
                'id'                => 103972,
                'name'              => 'Banco John Deere S.A.',
                'website'           => 'http://www.johndeere.com.br',
                'compensation_code' => 217,
                'created_at'        => $now,
            ],
            [
                'id'                => 105468,
                'name'              => 'Banco KDB S.A.',
                'website'           => 'http://www.bancokdb.com.br',
                'compensation_code' => 76,
                'created_at'        => $now,
            ],
            [
                'id'                => 104080,
                'name'              => 'Banco KEB HANA do Brasil S.A.',
                'website'           => 'http://www.bancokeb.com.br',
                'compensation_code' => 757,
                'created_at'        => $now,
            ],
            [
                'id'                => 105863,
                'name'              => 'Banco Komatsu S.A.',
                'website'           => 'http://www.bancokomatsu.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 104036,
                'name'              => 'Banco Luso Brasileiro S.A.',
                'website'           => 'http://www.lusobrasileiro.com.br',
                'compensation_code' => 600,
                'created_at'        => $now,
            ],
            [
                'id'                => 103986,
                'name'              => 'Banco Máxima S.A.',
                'website'           => 'http://www.bancomaxima.com.br',
                'compensation_code' => 243,
                'created_at'        => $now,
            ],
            [
                'id'                => 104977,
                'name'              => 'Banco Maxinvest S.A.',
                'website'           => 'http://www.bancomaxinvest.com.br',
                'compensation_code' => 720,
                'created_at'        => $now,
            ],
            [
                'id'                => 6,
                'name'              => 'Banco Mercantil de Investimentos S.A.',
                'website'           => 'http://www.mercantil.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 104012,
                'name'              => 'Banco Mercantil do Brasil S.A.',
                'website'           => 'http://www.mercantil.com.br',
                'compensation_code' => 389,
                'created_at'        => $now,
            ],
            [
                'id'                => 105516,
                'name'              => 'Banco Mercedes-Benz do Brasil S.A.',
                'website'           => 'http://www.bancomercedesbenz.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 104010,
                'name'              => 'Banco Europeu para a America Latina (BEAL) S.A.',
                'website'           => 'http://www.westlb.com',
                'compensation_code' => 370,
                'created_at'        => $now,
            ],
            [
                'id'                => 104071,
                'name'              => 'Banco Modal S.A.',
                'website'           => 'http://www.bancomodal.com.br',
                'compensation_code' => 746,
                'created_at'        => $now,
            ],
            [
                'id'                => 105459,
                'name'              => 'Banco Moneo S.A.',
                'website'           => 'http://www.bancomoneo.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 103951,
                'name'              => 'Banco Morgan Stanley S.A.',
                'website'           => 'http://www.morganstanley.com.br',
                'compensation_code' => 66,
                'created_at'        => $now,
            ],
            [
                'id'                => 105452,
                'name'              => 'Banco Nacional de Desenvolvimento Econômico e Social',
                'website'           => 'http://www.bndes.gov.br',
                'compensation_code' => 7,
                'created_at'        => $now,
            ],
            [
                'id'                => 104063,
                'name'              => 'Banco Neon S.A.',
                'website'           => 'http://www.banconeon.com.br',
                'compensation_code' => 735,
                'created_at'        => $now,
            ],
            [
                'id'                => 105643,
                'name'              => 'Banco Olé Bonsucesso Consignado S.A.',
                'website'           => 'http://www.oleconsignado.com.br',
                'compensation_code' => 169,
                'created_at'        => $now,
            ],
            [
                'id'                => 105510,
                'name'              => 'Banco Original do Agronegócio S.A.',
                'website'           => 'http://www.original.com.br',
                'compensation_code' => 79,
                'created_at'        => $now,
            ],
            [
                'id'                => 103968,
                'name'              => 'Banco Original S.A.',
                'website'           => 'http://www.original.com.br',
                'compensation_code' => 212,
                'created_at'        => $now,
            ],
            [
                'id'                => 104089,
                'name'              => 'Banco Ourinvest S.A.',
                'website'           => 'http://www.ourinvest.com.br',
                'compensation_code' => 712,
                'created_at'        => $now,
            ],
            [
                'id'                => 104042,
                'name'              => 'Banco PAN S.A.',
                'website'           => 'http://www.bancopan.com.br',
                'compensation_code' => 623,
                'created_at'        => $now,
            ],
            [
                'id'                => 104039,
                'name'              => 'Banco Paulista S.A.',
                'website'           => 'http://www.bancopaulista.com.br',
                'compensation_code' => 611,
                'created_at'        => $now,
            ],
            [
                'id'                => 104041,
                'name'              => 'Banco Pecúnia S.A.',
                'website'           => 'http://www.bancopecunia.com.br',
                'compensation_code' => 613,
                'created_at'        => $now,
            ],
            [
                'id'                => 104051,
                'name'              => 'Banco Pine S.A.',
                'website'           => 'http://www.pine.com',
                'compensation_code' => 643,
                'created_at'        => $now,
            ],
            [
                'id'                => 105052,
                'name'              => 'Banco Porto Real S.A.',
                'website'           => null,
                'compensation_code' => 658,
                'created_at'        => $now,
            ],
            [
                'id'                => 104098,
                'name'              => 'Banco PSA Finance Brasil S.A.',
                'website'           => 'http://www.bancopsa.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 104072,
                'name'              => 'Banco Rabobank International Brasil S.A.',
                'website'           => 'http://www.rabobank.com.br',
                'compensation_code' => 747,
                'created_at'        => $now,
            ],
            [
                'id'                => 105549,
                'name'              => 'Banco Randon S.A.',
                'website'           => 'http://www.bancorandon.com',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105664,
                'name'              => 'Banco RCI Brasil S.A.',
                'website'           => 'http://www.bancorenault.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 104046,
                'name'              => 'Banco Rendimento S.A.',
                'website'           => 'http://www.rendimento.com.br',
                'compensation_code' => 633,
                'created_at'        => $now,
            ],
            [
                'id'                => 104067,
                'name'              => 'Banco Ribeirão Preto S.A.',
                'website'           => 'http://www.brp.com.br',
                'compensation_code' => 741,
                'created_at'        => $now,
            ],
            [
                'id'                => 104088,
                'name'              => 'Banco Rodobens S.A.',
                'website'           => 'http://www.rodobens.com.br',
                'compensation_code' => 120,
                'created_at'        => $now,
            ],
            [
                'id'                => 104018,
                'name'              => 'Banco Safra S.A.',
                'website'           => 'http://www.safra.com.br',
                'compensation_code' => 422,
                'created_at'        => $now,
            ],
            [
                'id'                => 103925,
                'name'              => 'Banco Santander (Brasil) S.A.',
                'website'           => 'http://www.santander.com.br',
                'compensation_code' => 33,
                'created_at'        => $now,
            ],
            [
                'id'                => 104068,
                'name'              => 'Banco Semear S.A.',
                'website'           => 'http://www.bancosemear.com.br',
                'compensation_code' => 743,
                'created_at'        => $now,
            ],
            [
                'id'                => 104493,
                'name'              => 'Casa Bancária do Comércio e Indústria do Rio de Janeiro S.A.',
                'website'           => null,
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 104048,
                'name'              => 'Banco Sofisa S.A.',
                'website'           => 'http://www.sofisa.com.br',
                'compensation_code' => 637,
                'created_at'        => $now,
            ],
            [
                'id'                => 104021,
                'name'              => 'Banco Sumitomo Mitsui Brasileiro S.A.',
                'website'           => 'http://www.smbcgroup.com.br',
                'compensation_code' => 464,
                'created_at'        => $now,
            ],
            [
                'id'                => 105525,
                'name'              => 'Banco Topázio S.A.',
                'website'           => 'http://www.bancotopazio.com.br',
                'compensation_code' => 82,
                'created_at'        => $now,
            ],
            [
                'id'                => 104096,
                'name'              => 'Banco Toyota do Brasil S.A.',
                'website'           => 'http://www.bancotoyota.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 104047,
                'name'              => 'Banco Triângulo S.A.',
                'website'           => 'http://www.tribanco.com.br',
                'compensation_code' => 634,
                'created_at'        => $now,
            ],
            [
                'id'                => 104091,
                'name'              => 'Banco Tricury S.A.',
                'website'           => 'http://www.bancotricury.com.br',
                'compensation_code' => 18,
                'created_at'        => $now,
            ],
            [
                'id'                => 105864,
                'name'              => 'Banco Vipal S.A.',
                'website'           => 'http://www.bancovipal.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 104092,
                'name'              => 'Banco Volkswagen S.A.',
                'website'           => 'http://www.bancovw.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 104082,
                'name'              => 'Banco Volvo Brasil S.A.',
                'website'           => null,
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 104055,
                'name'              => 'Banco Votorantim S.A.',
                'website'           => 'http://www.bancovotorantim.com.br',
                'compensation_code' => 655,
                'created_at'        => $now,
            ],
            [
                'id'                => 104038,
                'name'              => 'Banco VR S.A.',
                'website'           => 'http://www.vrinvestimentos.com.br',
                'compensation_code' => 610,
                'created_at'        => $now,
            ],
            [
                'id'                => 105563,
                'name'              => 'Banco Western Union do Brasil S.A.',
                'website'           => 'http://www.bancowesternunion.com.br',
                'compensation_code' => 119,
                'created_at'        => $now,
            ],
            [
                'id'                => 105590,
                'name'              => 'Banco Woori Bank do Brasil S.A.',
                'website'           => 'http://www.wooribank.com.br',
                'compensation_code' => 124,
                'created_at'        => $now,
            ],
            [
                'id'                => 105518,
                'name'              => 'Banco Yamaha Motor do Brasil S.A.',
                'website'           => 'http://www.yamaha-motor.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105688,
                'name'              => 'Bancoob Distribuidora de Títulos e Valores Mobiliários LTDA.',
                'website'           => null,
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105690,
                'name'              => 'Banestes Distribuidora de Títulos e Valores Mobiliários S/A',
                'website'           => null,
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 103926,
                'name'              => 'BANESTES S.A. Banco do Estado do Espírito Santo',
                'website'           => 'http://www.banestes.com.br',
                'compensation_code' => 21,
                'created_at'        => $now,
            ],
            [
                'id'                => 104058,
                'name'              => 'Banif-Banco Internacional do Funchal (Brasil)S.A.',
                'website'           => 'http://www.banif.com.br',
                'compensation_code' => 719,
                'created_at'        => $now,
            ],
            [
                'id'                => 12,
                'name'              => 'Banif Banco de Investimento (Brasil) S.A.',
                'website'           => 'http://www.banif.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 104078,
                'name'              => 'Banco Merrill Lynch S.A.',
                'website'           => null,
                'compensation_code' => 755,
                'created_at'        => $now,
            ],
            [
                'id'                => 105693,
                'name'              => 'Banrisul S/A Corretora de Valores Mobiliários e Câmbio',
                'website'           => 'http://www.banrisulcorretora.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105696,
                'name'              => 'Barigui Companhia Hipotecária',
                'website'           => null,
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105695,
                'name'              => 'Barigui S.A. Crédito, Financiamento e Investimentos',
                'website'           => 'http://www.bariguifinanceira.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105698,
                'name'              => 'BB Gestão de Recursos - Distribuidora de Títulos e Valores Mobiliários S.A.',
                'website'           => 'http://www.bb.com.br/bbdtvm',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 10,
                'name'              => 'BB Banco de Investimento S.A.',
                'website'           => 'http://www.bb.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105700,
                'name'              => 'BB Leasing S/A Arrendamento Mercantil',
                'website'           => null,
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105511,
                'name'              => 'BBN Banco Brasileiro de Negócios S.A.',
                'website'           => 'http://www.rendimento.com.br',
                'compensation_code' => 81,
                'created_at'        => $now,
            ],
            [
                'id'                => 104033,
                'name'              => 'Banco Uno - E Brasil S.A.',
                'website'           => null,
                'compensation_code' => 496,
                'created_at'        => $now,
            ],
            [
                'id'                => 103991,
                'name'              => 'BCV - Banco de Crédito e Varejo S.A.',
                'website'           => 'http://www.bancobcv.com.br',
                'compensation_code' => 250,
                'created_at'        => $now,
            ],
            [
                'id'                => 105649,
                'name'              => 'BEC Distribuidora de Títulos e Valores Mobiliários LTDA.',
                'website'           => null,
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105650,
                'name'              => 'BEM - Distribuidora de Títulos e Valores Mobiliários LTDA.',
                'website'           => null,
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105701,
                'name'              => 'Besc-Distribuidora de Títulos e Valores Mobiliários SA-Bescval',
                'website'           => null,
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105634,
                'name'              => 'BEXS Banco de Câmbio S.A.',
                'website'           => 'http://www.bexs.com.br',
                'compensation_code' => 144,
                'created_at'        => $now,
            ],
            [
                'id'                => 105706,
                'name'              => 'Bexs Corretora de Câmbio S/A',
                'website'           => 'http://www.bexscorretora.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105651,
                'name'              => 'BMC Asset Management - Distribuidora de Títulos e Valores Mobiliários LTDA.',
                'website'           => 'http://www.bmc.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105707,
                'name'              => 'BMG Leasing S.A. - Arrendamento Mercantil',
                'website'           => 'http://www.bancobmg.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105576,
                'name'              => 'BMW Financeira S.A. - Crédito, Financiamento e Investimento',
                'website'           => 'http://www.bmwfs.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105709,
                'name'              => 'BMW Leasing do Brasil S.A. - Arrendamento Mercantil',
                'website'           => 'http://www.bmwfs.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105586,
                'name'              => 'BNY Mellon Banco S.A.',
                'website'           => 'http://www.bnymellon.com.br',
                'compensation_code' => 17,
                'created_at'        => $now,
            ],
            [
                'id'                => 105710,
                'name'              => 'BNY Mellon Serviços Financeiros Distribuidora de Títulos e Valores Mobiliários S.A.',
                'website'           => 'http://www.bnymellon.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 3,
                'name'              => 'BR Partners Banco de Investimento S.A.',
                'website'           => 'http://www.brap.com.br',
                'compensation_code' => 126,
                'created_at'        => $now,
            ],
            [
                'id'                => 105715,
                'name'              => 'BR Partners Corretora de Títulos e Valores Mobiliários S.A.',
                'website'           => null,
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105653,
                'name'              => 'Bradesco Leasing S.A. Arrecadamento Mercantil',
                'website'           => null,
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105654,
                'name'              => 'Bradesco S.A. Corretora de Títulos e Valores Mobiliários',
                'website'           => null,
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105762,
                'name'              => 'Bradesco-Kirton Corretora de Títulos e Valores Mobiliários S.A.',
                'website'           => null,
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105655,
                'name'              => 'BRAM - Bradesco Asset Management S.A. Distribuidora de Títulos e Valores Mobiliários',
                'website'           => null,
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105716,
                'name'              => 'Brasil Plural Corretora de Câmbio, Títulos e Valores Mobiliários S.A.',
                'website'           => 'http://www.brasilplural.com',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 104792,
                'name'              => 'Banco Prime S.A.',
                'website'           => null,
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 103952,
                'name'              => 'BRB - Banco de Brasília S.A.',
                'website'           => 'http://www.brb.com.br',
                'compensation_code' => 70,
                'created_at'        => $now,
            ],
            [
                'id'                => 105583,
                'name'              => 'BRB - Crédito, Financiamento e Investimento S.A.',
                'website'           => null,
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105719,
                'name'              => 'BRB - Distribuidora de Títulos e Valores Mobiliários SA',
                'website'           => 'http://www.brb.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 104848,
                'name'              => 'Banco Theca S.A.',
                'website'           => null,
                'compensation_code' => 737,
                'created_at'        => $now,
            ],
            [
                'id'                => 103977,
                'name'              => 'Banco Brascan S.A.',
                'website'           => 'http://www.bancobrascan.com.br',
                'compensation_code' => 225,
                'created_at'        => $now,
            ],
            [
                'id'                => 105723,
                'name'              => 'BTG Pactual Asset Management S.A. Distribuidora de Títulos e Valores Mobiliários',
                'website'           => 'http://www.btgpactual.com',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 103967,
                'name'              => 'Banco Sistema S.A.',
                'website'           => null,
                'compensation_code' => 211,
                'created_at'        => $now,
            ],
            [
                'id'                => 105840,
                'name'              => 'BTG Pactual Serviços Financeiros S.A. Distribuidora de Títulos e Valores Mobiliários',
                'website'           => 'http://www.btgpactual.com',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105568,
                'name'              => 'BV Financeira S.A. - Crédito, Financiamento e Investimento',
                'website'           => 'http://www.bvfinanceira.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105831,
                'name'              => 'BV Leasing - Arrendamento Mercantil S.A.',
                'website'           => 'http://www.votorantimfinanças.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105739,
                'name'              => 'Ca Indosuez Wealth (Brazil) S.A. Distribuidora de Títulos e Valores Mobiliários',
                'website'           => 'http://www.creditagricoledtvm.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 103953,
                'name'              => 'Caixa Econômica Federal',
                'website'           => 'http://www.caixa.gov.br',
                'compensation_code' => 104,
                'created_at'        => $now,
            ],
            [
                'id'                => 105727,
                'name'              => 'CCB Brasil Arrendamento Mercantil S/A',
                'website'           => null,
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105728,
                'name'              => 'CCB Brasil Distribuidora de Títulos e Valores Mobiliários S.A.',
                'website'           => null,
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105726,
                'name'              => 'CGD Investimentos Corretora de Valores e Câmbio S.A.',
                'website'           => null,
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 104002,
                'name'              => 'China Construction Bank (Brasil) Banco Múltiplo S.A.',
                'website'           => 'http://www.br.ccb.com',
                'compensation_code' => 320,
                'created_at'        => $now,
            ],
            [
                'id'                => 105708,
                'name'              => 'Cifra S.A. Crédito, Financiamento e Investimento',
                'website'           => 'http://www.bancocifra.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105730,
                'name'              => 'Citibank Distribuidora de Títulos e Valores Mobiliários S.A',
                'website'           => 'http://www.citibank.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105731,
                'name'              => 'Citibank Leasing S.A - Arrendamento Mercantil',
                'website'           => 'http://www.citibank.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 104024,
                'name'              => 'Citibank N.A.',
                'website'           => 'http://www.citibank.com',
                'compensation_code' => 477,
                'created_at'        => $now,
            ],
            [
                'id'                => 105847,
                'name'              => 'Citigroup Global Markets Brasil, Corretora de Câmbio, Títulos e Valores Mobiliários S.A.',
                'website'           => 'http://www.citibank.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105732,
                'name'              => 'CM Capital Markets Corretora de Câmbio, Títulos e Valores Mobiliários LTDA',
                'website'           => 'http://www.cmcapitalmarkets.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105733,
                'name'              => 'CM Capital Markets Distribuidora de Títulos e Valores Mobiliários LTDA',
                'website'           => 'http://www.cmcapitalmarkets.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105735,
                'name'              => 'COIN-Distribuidora de Títulos e Valores Mobiliários LTDA',
                'website'           => 'http://www.coinvalores.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105734,
                'name'              => 'Coinvalores Corretora de Câmbio e Valores Mobiliários LTDA.',
                'website'           => 'http://www.coinvalores.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105865,
                'name'              => 'Commerzbank Brasil S.A. - Banco Múltiplo',
                'website'           => 'http://www.commerzbank.com.br',
                'compensation_code' => 163,
                'created_at'        => $now,
            ],
            [
                'id'                => 105737,
                'name'              => 'Companhia Hipotecária Piratini - CHP',
                'website'           => 'http://www.chphipotecaria.com.br/',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105736,
                'name'              => 'Companhia Província de Crédito Imobiliário',
                'website'           => 'http://www.ciaprovincia.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105738,
                'name'              => 'Confidence Corretora de Câmbio S.A.',
                'website'           => 'http://www.confidencecambio.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105807,
                'name'              => 'Cotação Distribuidora de Títulos e Valores Mobiliários S.A',
                'website'           => 'http://www.cotacao.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105656,
                'name'              => 'Crediare S.A. Crédito, Financiamento e Investimento',
                'website'           => 'http://www.crediare.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105742,
                'name'              => 'Credit Suisse (Brasil) S.A. Corretora de Títulos e Valores Mobiliários',
                'website'           => null,
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105743,
                'name'              => 'Credit Suisse Hedging-Griffo Corretora de Valores S.A',
                'website'           => 'http://www.cshg.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105744,
                'name'              => 'Dacasa Financeira S.A.-Soc. de Créd. Financ. e Investimento',
                'website'           => 'http://www.dacasa.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105517,
                'name'              => 'Banco Commercial Investment Trus do Brasil S.A.',
                'website'           => null,
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 104027,
                'name'              => 'Deutsche Bank S.A. - Banco Alemão',
                'website'           => 'http://www.deutsche-bank.com.br',
                'compensation_code' => 487,
                'created_at'        => $now,
            ],
            [
                'id'                => 105670,
                'name'              => 'Dibens Leasing S.A. Arrendamento Mercantil',
                'website'           => 'http://www.itau.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105764,
                'name'              => 'Distribuidora Intercap de Títulos e Valores Mobiliários S.A.',
                'website'           => 'http://www.intercap.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105754,
                'name'              => 'Estrela Mineira Crédito, Financiamento e Investimento S/A',
                'website'           => null,
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105748,
                'name'              => 'Fator S.A. - Corretora de Valores',
                'website'           => 'http://www.bancofator.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105575,
                'name'              => 'Finamax S.A. - Crédito, Financiamento e Investimento',
                'website'           => 'http://www.finamax.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105686,
                'name'              => 'Financeira Alfa S.A. Crédito, Financiamento e Investimentos',
                'website'           => 'http://www.alfanet.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105671,
                'name'              => 'Financeira Itaú CBD S.A. Crédito, Financiamento e Investimento',
                'website'           => 'http://www.itau.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 104060,
                'name'              => 'Finansinos S.A. - Crédito, Financ. e Investimento',
                'website'           => null,
                'compensation_code' => 725,
                'created_at'        => $now,
            ],
            [
                'id'                => 105797,
                'name'              => 'Finaxis Corretora de Títulos e Valores Mobiliários S.A.',
                'website'           => 'http://www.personaltrader.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105749,
                'name'              => 'Gazincred S.A. Sociedade de Crédito, Financiamento e Investimento',
                'website'           => 'http://www.gazincred.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105717,
                'name'              => 'Geração Futuro Corretora de Valores SA.',
                'website'           => 'http://www.gerafuturo.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105751,
                'name'              => 'Golcred S/A - Crédito, Financiamento e Investimento',
                'website'           => 'http://www.golcred.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 103949,
                'name'              => 'Goldman Sachs do Brasil Banco Múltiplo S.A.',
                'website'           => 'http://www.goldmansachs.com',
                'compensation_code' => 64,
                'created_at'        => $now,
            ],
            [
                'id'                => 105753,
                'name'              => 'Goldman Sachs do Brasil Corretora de Títulos e Valores Mobiliárias S.A.',
                'website'           => 'http://www.gs.com',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105868,
                'name'              => 'Gradual Corretora de Câmbio,Títulos e Valores Mobiliários S.A.',
                'website'           => 'http://www.gradualcorretora.com.br',
                'compensation_code' => 135,
                'created_at'        => $now,
            ],
            [
                'id'                => 105765,
                'name'              => 'Guide Investimentos S.A. - Corretora de Valores',
                'website'           => 'http://www.indusval.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105756,
                'name'              => 'H H Picchioni S/A Corretora de Câmbio e Valores Mobiliários',
                'website'           => 'http://www.picchioni.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 104913,
                'name'              => 'Haitong Banco de Investimento do Brasil S.A.',
                'website'           => 'http://www.haitongib.com.br',
                'compensation_code' => 78,
                'created_at'        => $now,
            ],
            [
                'id'                => 105704,
                'name'              => 'Haitong do Brasil Distribuidora de Títulos e Valores Mobiliários S.A.',
                'website'           => 'http://www.haitongib.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105705,
                'name'              => 'Haitong Securities do Brasil Corretora de Câmbio e Valores Mobiliários S.A.',
                'website'           => 'http://www.haitongib.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 103947,
                'name'              => 'Hipercard Banco Múltiplo S.A.',
                'website'           => 'http://www.hipercard.com.br',
                'compensation_code' => 62,
                'created_at'        => $now,
            ],
            [
                'id'                => 105760,
                'name'              => 'Honda Leasing S.A. - Arrendamento Mercantil',
                'website'           => 'http://www.hondaleasing.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105758,
                'name'              => 'HS Financeira S/A Crédito, Financiamento e Investimentos',
                'website'           => 'http://www.hsfinanceira.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105845,
                'name'              => 'HSBC Brasil S.A. - Banco de Investimento',
                'website'           => null,
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 9,
                'name'              => 'ICBC do Brasil Banco Múltiplo S.A.',
                'website'           => 'http://www.icbcbr.com.br',
                'compensation_code' => 132,
                'created_at'        => $now,
            ],
            [
                'id'                => 105763,
                'name'              => 'Industrial do Brasil Distribuidora de Títulos e Valores Mobiliários LTDA.',
                'website'           => 'http://www.bancoindustrial.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 104029,
                'name'              => 'ING Bank N.V.',
                'website'           => 'http://www.ing.com',
                'compensation_code' => 492,
                'created_at'        => $now,
            ],
            [
                'id'                => 105766,
                'name'              => 'ING Corretora de Câmbio e Títulos S.A.',
                'website'           => 'http://www.ing.com',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105767,
                'name'              => 'Intermedium Distribuidora de Títulos e Valores Mobiliários LTDA.',
                'website'           => 'http://www.intermedium.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105862,
                'name'              => 'Intesa Sanpaolo Brasil S.A. - Banco Múltiplo',
                'website'           => 'http://www.intesasanpaolobrasil.com.br',
                'compensation_code' => 139,
                'created_at'        => $now,
            ],
            [
                'id'                => 105672,
                'name'              => 'Intrag Distribuidora de Títulos e Valores Mobiliários LTDA.',
                'website'           => 'http://www.intrag.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105673,
                'name'              => 'Itaú Corretora de Valores S.A.',
                'website'           => 'http://www.itaucor.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105679,
                'name'              => 'Itaú Distribuidora de Títulos e Valores Mobiliários S.A.',
                'website'           => 'http://www.itau.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 104004,
                'name'              => 'Banco Francês e Brasileiro S.A.',
                'website'           => null,
                'compensation_code' => 346,
                'created_at'        => $now,
            ],
            [
                'id'                => 104003,
                'name'              => 'Itaú Unibanco S.A.',
                'website'           => 'http://www.itau.com.br',
                'compensation_code' => 341,
                'created_at'        => $now,
            ],
            [
                'id'                => 105674,
                'name'              => 'Itauvest Distribuidora de Títulos e Valores Mobiliários S.A.',
                'website'           => 'http://www.itau.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 1,
                'name'              => 'J. Malucelli Distribuidora de Títulos e Valores Mobiliários LTDA.',
                'website'           => 'http://www.paranaasset.com',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105814,
                'name'              => 'J. Safra Corretora de Valores e Câmbio LTDA',
                'website'           => 'http://www.safra.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105852,
                'name'              => 'J.P. Morgan Corretora de Câmbio e Valores Mobiliários S.A.',
                'website'           => 'http://www.jpmorgan.com',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105849,
                'name'              => 'J.P. Morgan S.A. - Distribuidora de Títulos e Valores Mobiliários',
                'website'           => 'http://www.jpmorgan.com',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105768,
                'name'              => 'John Deere Distribuidora de Títulos e Valores Mobiliários LTDA.',
                'website'           => null,
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 104028,
                'name'              => 'JPMorgan Chase Bank, National Association',
                'website'           => 'http://www.jpmorganchase.com',
                'compensation_code' => 488,
                'created_at'        => $now,
            ],
            [
                'id'                => 105769,
                'name'              => 'Lecca Crédito, Financiamento e Investimento S/A',
                'website'           => 'http://www.lecca.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105770,
                'name'              => 'Lecca Distribuidora de Títulos e Valores Mobiliários LTDA',
                'website'           => 'http://www.leccadtvm.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105687,
                'name'              => 'LLA - Distribuidora de Títulos e Valores Mobiliários LTDA.',
                'website'           => 'http://www.lla.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105676,
                'name'              => 'Luizacred S.A. Sociedade de Crédito, Financiamento e Investimento',
                'website'           => 'http://www.itau.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105787,
                'name'              => 'Máxima S.A. Corretora de Câmbio, Títulos e Valores Mobiliários',
                'website'           => 'http://www.maximacctvm.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105779,
                'name'              => 'Mercantil do Brasil Corretora S.A. - Câmbio, Títulos e Valores Mobiliários',
                'website'           => 'http://www.mercantil.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105780,
                'name'              => 'Mercantil do Brasil Distribuidora S.A. - Títulos e Valores Mobiliários',
                'website'           => 'http://www.mercantil.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105781,
                'name'              => 'Mercantil do Brasil Financeira S.A - Crédito, Financiamento e Investimentos',
                'website'           => 'http://www.mercantil.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105784,
                'name'              => 'Mercedes-Benz Leasing do Brasil Arrendamento Mercantil S.A.',
                'website'           => 'http://www.bancomercedesbenz.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105711,
                'name'              => 'Merrill Lynch S.A. Corretora de Títulos e Valores Mobiliários',
                'website'           => null,
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105677,
                'name'              => 'Microinvest S.A. Sociedade de Crédito ao Microempreendedor',
                'website'           => 'http://www.itau.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105785,
                'name'              => 'Modal Distribuidora de Títulos e Valores Mobiliários LTDA',
                'website'           => 'http://www.modalmais.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105786,
                'name'              => 'Morgan Stanley Corretora de Títulos e Valores Mobiliários S.A.',
                'website'           => null,
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105633,
                'name'              => 'MS Bank S.A. Banco de Câmbio',
                'website'           => 'http://www.msbank.com.br',
                'compensation_code' => 128,
                'created_at'        => $now,
            ],
            [
                'id'                => 105512,
                'name'              => 'Natixis Brasil S.A. Banco Múltiplo',
                'website'           => 'http://www.br.natixis.com',
                'compensation_code' => 14,
                'created_at'        => $now,
            ],
            [
                'id'                => 104077,
                'name'              => 'Novo Banco Continental S.A. - Banco Múltiplo',
                'website'           => 'http://www.nbcbank.com.br',
                'compensation_code' => 753,
                'created_at'        => $now,
            ],
            [
                'id'                => 105573,
                'name'              => 'Omni SA Crédito Financiamento Investimento',
                'website'           => 'http://www.omni.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105790,
                'name'              => 'Omni S.A. Arrendamento Mercantil',
                'website'           => 'http://www.omni.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105791,
                'name'              => 'Ourinvest Distribuidora de Títulos e Valores Mobiliários S.A.',
                'website'           => 'http://www.ourinvest.com.br/pt',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105793,
                'name'              => 'PAN Arrendamento Mercantil S.A.',
                'website'           => 'http://www.bancopan.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 103993,
                'name'              => 'Paraná Banco S.A.',
                'website'           => 'http://www.paranabanco.com.br',
                'compensation_code' => 254,
                'created_at'        => $now,
            ],
            [
                'id'                => 105757,
                'name'              => 'PBM - Picchioni - Belgo - Mineira Distribuidora de Títulos e Valres Mobiliários S/A',
                'website'           => null,
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105796,
                'name'              => 'Pernambucanas Financiadora S.A. - Crédito, Financiamento e Investimento',
                'website'           => null,
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105798,
                'name'              => 'Pine Investimentos Distribuidoras de Títulos e Valores Mobiliários LTDA',
                'website'           => 'http://www.bancopine.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105799,
                'name'              => 'Planner Corretora de Valores S.A.',
                'website'           => 'http://www.planner.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105800,
                'name'              => 'Planner Sociedade de Crédito ao Microempreendedor S.A.',
                'website'           => 'http://www.planner.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105801,
                'name'              => 'Planner Trustee Distribuidora de Títulos e Valores Mobiliários LTDA.',
                'website'           => 'http://www.planner.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105804,
                'name'              => 'Portopar Distribuidora de Títulos e Valores Mobiliários LTDA',
                'website'           => 'http://www.portopar.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105802,
                'name'              => 'PortoSeg S.A. - Crédito, Financiamento e Investimento',
                'website'           => 'http://www.portofinanciamento.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105789,
                'name'              => 'Positiva Corretora de Câmbio, Títulos e Valores Mobiliários S.A.',
                'website'           => 'http://www.positivadtvm.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105815,
                'name'              => 'Safra Leasing S.A. Arrendamento Mercantil',
                'website'           => 'http://www.safra.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105577,
                'name'              => 'Santana S.A. - Crédito, Financiamento e Investimento',
                'website'           => 'http://www.santana-shopcred.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105666,
                'name'              => 'Santander Brasil Asset Manag Distribuidora de Títulos e Valores Mobiliários S.A.',
                'website'           => 'http://www.santander.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105667,
                'name'              => 'Santander Corretora de Câmbio e Valores Mobiliários S.A.',
                'website'           => 'http://www.santander.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105805,
                'name'              => 'PSA Finance Arrendamento Mercantil S.A.',
                'website'           => 'http://www.bancopsa.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105668,
                'name'              => 'Santander Leasing S.A. Arrendamento Mercantil',
                'website'           => 'http://www.santander.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105669,
                'name'              => 'Santander Securities Services Brasil Distribuidora de Títulos e Valores Mobiliários S.A.',
                'website'           => 'http://www.santander.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105816,
                'name'              => 'Santinvest S.A - Crédito, Financiamento e Investimentos',
                'website'           => 'http://www.santinvest.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105542,
                'name'              => 'Scania Banco S.A.',
                'website'           => 'http://www.scaniabanco.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 104075,
                'name'              => 'Scotiabank Brasil S.A. Banco Múltiplo',
                'website'           => 'http://www.br.scotiabank.com',
                'compensation_code' => 751,
                'created_at'        => $now,
            ],
            [
                'id'                => 105824,
                'name'              => 'SG Equipment Finance S.A. Arrendamento Mercantil',
                'website'           => null,
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105820,
                'name'              => 'Sinosserra Financeira S/A - Sociedade de Crédito, Financiamento e Investimento',
                'website'           => 'http://www.sinosserrafinanceira.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105826,
                'name'              => 'Socopa Sociedade Corretora Paulista S.A.',
                'website'           => 'http://www.socopa.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105827,
                'name'              => 'Sofisa S.A. Crédito, Financiamento e Investimento',
                'website'           => null,
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105546,
                'name'              => 'Standard Chartered Bank (Brasil) S/A – Banco de In',
                'website'           => 'http://www.standardchartered.com',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105589,
                'name'              => 'UBS Brasil Banco de Investimento S.A.',
                'website'           => 'http://www.ubs.com',
                'compensation_code' => 129,
                'created_at'        => $now,
            ],
            [
                'id'                => 105828,
                'name'              => 'UBS Brasil Corretora de Câmbio, Títulos e Valores Mobiliários S.A.',
                'website'           => 'http://www.ubs.com/br/pt/ubs_corretora.html',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105745,
                'name'              => 'Uniletra Corretora de Câmbio, Títulos e Valores Mobiliários S.A.',
                'website'           => 'http://www.uniletra.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105832,
                'name'              => 'Votorantim - Corretora de Títulos e Valores Mobiliários LTDA.',
                'website'           => 'http://www.votorantimfinancas.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105833,
                'name'              => 'Votorantim Asset Management Distribuidora de Títulos e Valores Mobiliários LTDA',
                'website'           => 'http://www.vam.com.br',
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105834,
                'name'              => 'VR Distribuidora de Títulos e Valores Mobiliários LTDA.',
                'website'           => null,
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105835,
                'name'              => 'Western Union Corretora de Câmbio S.A.',
                'website'           => null,
                'compensation_code' => null,
                'created_at'        => $now,
            ],
            [
                'id'                => 105837,
                'name'              => 'XP Investimentos Corretora de Câmbio, Títulos e Valores Mobiliários S/A',
                'website'           => 'http://www.xpi.com.br',
                'compensation_code' => null,
            ],
        ]);

    }

}
